### ISSUE TITLE
Finishes, but now 

### ISSUE THREAD

**Issue by fsanzl** [ofmgraz/ofm-arche#2]
```
Latest Additions
[Choralhandschriften der Zentralbibliothek der Wiener Franziskanerprovinz Graz](http://localhost/browser/detail/19591)
 Type: acdh:TopCollection
today Available Date: 12 Apr 2024
```

Yet, after opening it:

```
Resource does not exists!
```

**Comment by csae8092** [comment]
the gui shipped with arche-localhost-utils is currently under heavy development and therefore not suitable for checking ingested results. I always use the ARCHE-API output for checking which gives us anyway a more direct view on the ingested data; something like 
http://localhost/api/api/19591/metadata should work

and congrets for the successful ingestion!!!!

**Comment by fsanzl** [comment]
It seems well formed. The hierarchy is there. :-)
